import type { Locale } from "@/lib/i18n";

type CopyByLocale<T> = Record<Locale, T>;

export const copy = {
  home: {
    heroKicker: {
      "en-US": "Diversified operating + investment company",
      "en-GB": "Diversified operating + investment company",
      es: "Compañía operadora e inversora diversificada",
      fr: "Société d’exploitation et d’investissement diversifiée",
      de: "Diversifizierte Betriebs- und Investmentgesellschaft",
    },
    heroTitle: {
      "en-US": "NaviVision builds, operates, and invests across talent, software, real estate, and startups.",
      "en-GB": "NaviVision builds, operates, and invests across talent, software, real estate, and startups.",
      es: "NaviVision construye, opera e invierte en talento, software, bienes raíces y startups.",
      fr: "NaviVision conçoit, exploite et investit dans les talents, les logiciels, l’immobilier et les startups.",
      de: "NaviVision entwickelt, betreibt und investiert in Talent, Software, Immobilien und Start-ups.",
    },
    heroSubtitle: {
      "en-US":
        "We partner with teams to hire exceptional people, launch products, scale SaaS businesses, and operate a disciplined real estate portfolio, while investing in founders we believe in.",
      "en-GB":
        "We partner with teams to hire exceptional people, launch products, scale SaaS businesses, and operate a disciplined real estate portfolio, while investing in founders we believe in.",
      es: "Trabajamos con equipos para contratar talento excepcional, lanzar productos, escalar negocios SaaS y operar una cartera inmobiliaria disciplinada, mientras invertimos en fundadores en los que creemos.",
      fr: "Nous aidons les équipes à recruter des talents, lancer des produits, développer des activités SaaS et gérer un portefeuille immobilier avec discipline, tout en investissant dans des fondateurs en qui nous croyons.",
      de: "Wir unterstützen Teams dabei, herausragende Talente einzustellen, Produkte zu launchen, SaaS-Unternehmen zu skalieren und ein diszipliniertes Immobilienportfolio zu betreiben – und investieren zugleich in Gründer, an die wir glauben.",
    },
    ctaPrimary: {
      "en-US": "Start a conversation",
      "en-GB": "Start a conversation",
      es: "Iniciar una conversación",
      fr: "Engager la conversation",
      de: "Kontakt aufnehmen",
    },
    ctaSecondary: {
      "en-US": "Explore our portfolio",
      "en-GB": "Explore our portfolio",
      es: "Explorar nuestro portafolio",
      fr: "Découvrir notre portefeuille",
      de: "Portfolio ansehen",
    },

    whatWeDoTitle: {
      "en-US": "What we do",
      "en-GB": "What we do",
      es: "Qué hacemos",
      fr: "Ce que nous faisons",
      de: "Was wir tun",
    },
    whatWeDoSubtitle: {
      "en-US": "Four verticals, one operating mindset.",
      "en-GB": "Four verticals, one operating mindset.",
      es: "Cuatro verticales, una mentalidad operativa.",
      fr: "Quatre verticales, une même approche opérationnelle.",
      de: "Vier Bereiche, ein operatives Mindset.",
    },
    cardTalentTitle: {
      "en-US": "Talent & Hiring",
      "en-GB": "Talent & Hiring",
      es: "Talento y contratación",
      fr: "Talent et recrutement",
      de: "Talent & Recruiting",
    },
    cardTalentBody: {
      "en-US":
        "Hiring support for companies and career opportunities for technical and operational talent.",
      "en-GB":
        "Hiring support for companies and career opportunities for technical and operational talent.",
      es: "Apoyo de contratación para empresas y oportunidades profesionales para talento técnico y operativo.",
      fr: "Recrutement pour les entreprises et opportunités pour les profils techniques et opérationnels.",
      de: "Hiring-Support für Unternehmen und Karrieremöglichkeiten für technische und operative Talente.",
    },
    cardSoftwareTitle: {
      "en-US": "Custom SaaS",
      "en-GB": "Custom SaaS",
      es: "SaaS a medida",
      fr: "SaaS sur mesure",
      de: "Individuelles SaaS",
    },
    cardSoftwareBody: {
      "en-US": "We build and operate software with a focus on durability and customer outcomes.",
      "en-GB": "We build and operate software with a focus on durability and customer outcomes.",
      es: "Construimos y operamos software con foco en la durabilidad y los resultados del cliente.",
      fr: "Nous concevons et exploitons des logiciels avec un focus sur la durabilité et la valeur client.",
      de: "Wir entwickeln und betreiben Software mit Fokus auf Langlebigkeit und messbare Ergebnisse.",
    },
    cardRealEstateTitle: {
      "en-US": "Real Estate",
      "en-GB": "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      de: "Immobilien",
    },
    cardRealEstateBody: {
      "en-US":
        "Long-term ownership with an operator’s attention to maintenance, tenants, and neighborhoods.",
      "en-GB":
        "Long-term ownership with an operator’s attention to maintenance, tenants, and neighbourhoods.",
      es: "Propiedad a largo plazo con atención operativa al mantenimiento, inquilinos y vecindarios.",
      fr: "Détention long terme avec une attention d’opérateur pour la maintenance, les occupants et les quartiers.",
      de: "Langfristiger Besitz mit operativem Fokus auf Instandhaltung, Mieter und Standorte.",
    },
    cardInvestmentsTitle: {
      "en-US": "Investments",
      "en-GB": "Investments",
      es: "Inversiones",
      fr: "Investissements",
      de: "Investments",
    },
    cardInvestmentsBody: {
      "en-US": "Targeted bets in early-stage teams, with a preference for founders who ship.",
      "en-GB": "Targeted bets in early-stage teams, with a preference for founders who ship.",
      es: "Apuestas selectivas en equipos tempranos, con preferencia por fundadores que ejecutan.",
      fr: "Paris ciblés sur des équipes early stage, avec une préférence pour les fondateurs qui livrent.",
      de: "Gezielte Investments in Early-Stage-Teams – bevorzugt Gründer, die liefern.",
    },
    cardExplore: {
      "en-US": "Explore",
      "en-GB": "Explore",
      es: "Explorar",
      fr: "Découvrir",
      de: "Entdecken",
    },
    holdingTitle: {
      "en-US": "A modern holding company",
      "en-GB": "A modern holding company",
      es: "Una holding moderna",
      fr: "Une holding moderne",
      de: "Eine moderne Holding",
    },
    holdingSubtitle: {
      "en-US": "We’re operators first, built for compounding.",
      "en-GB": "We’re operators first, built for compounding.",
      es: "Somos operadores primero, diseñados para el crecimiento acumulativo.",
      fr: "Des opérateurs avant tout, conçus pour une croissance durable.",
      de: "Operator-first – auf langfristiges Wachstum ausgelegt.",
    },
    buildTitle: {
      "en-US": "Build",
      "en-GB": "Build",
      es: "Construir",
      fr: "Construire",
      de: "Bauen",
    },
    buildBody: {
      "en-US": "Launch products and internal tools, then iterate with measurable feedback loops.",
      "en-GB": "Launch products and internal tools, then iterate with measurable feedback loops.",
      es: "Lanzamos productos y herramientas internas, y luego iteramos con ciclos de feedback medibles.",
      fr: "Nous lançons des produits et des outils internes, puis itérons avec des boucles de feedback mesurables.",
      de: "Wir launchen Produkte und interne Tools und iterieren mit messbaren Feedback-Loops.",
    },
    operateTitle: {
      "en-US": "Operate",
      "en-GB": "Operate",
      es: "Operar",
      fr: "Exploiter",
      de: "Betreiben",
    },
    operateBody: {
      "en-US": "Stable processes, reliable systems, and attention to unit economics across businesses.",
      "en-GB": "Stable processes, reliable systems, and attention to unit economics across businesses.",
      es: "Procesos estables, sistemas confiables y atención a la economía unitaria en cada negocio.",
      fr: "Des processus stables, des systèmes fiables et une attention à l’économie unitaire.",
      de: "Stabile Prozesse, verlässliche Systeme und Fokus auf Unit Economics.",
    },
    investTitle: {
      "en-US": "Invest",
      "en-GB": "Invest",
      es: "Invertir",
      fr: "Investir",
      de: "Investieren",
    },
    investBody: {
      "en-US": "Capital and support for businesses with durable advantages and high-integrity teams.",
      "en-GB": "Capital and support for businesses with durable advantages and high-integrity teams.",
      es: "Capital y apoyo para negocios con ventajas duraderas y equipos con alta integridad.",
      fr: "Capital et soutien pour des entreprises avec des avantages durables et des équipes intègres.",
      de: "Kapital und Unterstützung für Unternehmen mit dauerhaften Vorteilen und integeren Teams.",
    },
    workWithTitle: {
      "en-US": "Work with NaviVision",
      "en-GB": "Work with NaviVision",
      es: "Trabaje con NaviVision",
      fr: "Travailler avec NaviVision",
      de: "Mit NaviVision arbeiten",
    },
    workWithBody: {
      "en-US":
        "Whether you’re hiring, looking for your next role, or exploring partnerships, start here.",
      "en-GB":
        "Whether you’re hiring, looking for your next role, or exploring partnerships, start here.",
      es: "Ya sea que esté contratando, buscando su próximo rol o explorando alianzas, empiece aquí.",
      fr: "Que vous recrutiez, cherchiez un poste ou envisagiez un partenariat, commencez ici.",
      de: "Ob Hiring, nächste Rolle oder Partnerschaft – starten Sie hier.",
    },
    workWithCtaJobs: {
      "en-US": "View open roles",
      "en-GB": "View open roles",
      es: "Ver roles abiertos",
      fr: "Voir les postes ouverts",
      de: "Offene Rollen ansehen",
    },
    workWithCtaContact: {
      "en-US": "Contact us",
      "en-GB": "Contact us",
      es: "Contáctenos",
      fr: "Contactez-nous",
      de: "Kontakt",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  about: {
    kicker: {
      "en-US": "About",
      "en-GB": "About",
      es: "Acerca de",
      fr: "À propos",
      de: "Über uns",
    },
    title: {
      "en-US": "We’re a hands-on operator with a long-term view.",
      "en-GB": "We’re a hands-on operator with a long-term view.",
      es: "Somos operadores prácticos con una visión de largo plazo.",
      fr: "Nous sommes des opérateurs de terrain, avec une vision long terme.",
      de: "Wir sind Betreiber aus der Praxis – mit langfristigem Blick.",
    },
    intro: {
      "en-US":
        "NaviVision is a diversified operating and investment company. We build and support businesses that can compound over time through great teams, sound economics, and disciplined execution.",
      "en-GB":
        "NaviVision is a diversified operating and investment company. We build and support businesses that can compound over time through great teams, sound economics, and disciplined execution.",
      es: "NaviVision es una compañía operadora e inversora diversificada. Construimos y apoyamos negocios que pueden crecer con el tiempo a través de grandes equipos, una economía sólida y una ejecución disciplinada.",
      fr: "NaviVision est une société d’exploitation et d’investissement diversifiée. Nous construisons et accompagnons des entreprises capables de croître durablement grâce à de grandes équipes, une économie saine et une exécution disciplinée.",
      de: "NaviVision ist eine diversifizierte Betriebs- und Investmentgesellschaft. Wir bauen Unternehmen auf und unterstützen sie dabei, langfristig zu wachsen – mit starken Teams, solider Wirtschaftlichkeit und disziplinierter Umsetzung.",
    },
    focusTitle: {
      "en-US": "Our focus",
      "en-GB": "Our focus",
      es: "Nuestro enfoque",
      fr: "Nos priorités",
      de: "Unser Fokus",
    },
    focusSubtitle: {
      "en-US":
        "Each vertical stands on its own, but we share playbooks across all of them.",
      "en-GB":
        "Each vertical stands on its own, but we share playbooks across all of them.",
      es: "Cada vertical se sostiene por sí mismo, pero compartimos prácticas entre todos.",
      fr: "Chaque verticale est autonome, mais nous partageons des méthodes entre elles.",
      de: "Jede Sparte steht für sich, doch wir teilen Playbooks über alle Bereiche hinweg.",
    },
    teamTitle: {
      "en-US": "Team",
      "en-GB": "Team",
      es: "Equipo",
      fr: "Équipe",
      de: "Team",
    },
    teamSubtitle: {
      "en-US": "Operator-led and built for long-term compounding.",
      "en-GB": "Operator-led and built for long-term compounding.",
      es: "Liderado por operadores y diseñado para el crecimiento a largo plazo.",
      fr: "Portée par des opérateurs, conçue pour une croissance durable.",
      de: "Operator-led und auf langfristiges Wachstum ausgelegt.",
    },
    profileSoon: {
      "en-US": "Profile coming soon.",
      "en-GB": "Profile coming soon.",
      es: "Perfil próximamente.",
      fr: "Profil à venir.",
      de: "Profil folgt in Kürze.",
    },
    metaTitle: {
      "en-US": "About",
      "en-GB": "About",
      es: "Acerca de",
      fr: "À propos",
      de: "Über uns",
    },
    metaDescription: {
      "en-US": "Learn about NaviVision and our operating focus across talent, software, real estate, and investments.",
      "en-GB": "Learn about NaviVision and our operating focus across talent, software, real estate, and investments.",
      es: "Conozca NaviVision y nuestro enfoque operativo en talento, software, bienes raíces e inversiones.",
      fr: "Découvrez NaviVision et notre approche opérationnelle autour des talents, des logiciels, de l’immobilier et des investissements.",
      de: "Erfahren Sie mehr über NaviVision und unseren operativen Fokus auf Talent, Software, Immobilien und Investments.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  contact: {
    title: {
      "en-US": "Let’s talk.",
      "en-GB": "Let’s talk.",
      es: "Hablemos.",
      fr: "Discutons.",
      de: "Lassen Sie uns sprechen.",
    },
    intro: {
      "en-US":
        "Use the form below to reach our team. If you’re a company looking to hire, a candidate exploring roles, or a founder seeking partnership, include the basics and we’ll follow up.",
      "en-GB":
        "Use the form below to reach our team. If you’re a company looking to hire, a candidate exploring roles, or a founder seeking partnership, include the basics and we’ll follow up.",
      es: "Use el formulario para contactar con nuestro equipo. Si es una empresa que busca contratar, una persona explorando oportunidades o un fundador buscando colaboración, comparta lo básico y le responderemos.",
      fr: "Utilisez le formulaire pour contacter notre équipe. Que vous recrutiez, que vous recherchiez un poste ou que vous souhaitiez un partenariat, partagez l’essentiel et nous reviendrons vers vous.",
      de: "Nutzen Sie das Formular, um unser Team zu erreichen. Ob Sie einstellen möchten, eine Rolle suchen oder eine Partnerschaft anfragen – teilen Sie die wichtigsten Informationen, und wir melden uns.",
    },
    includeTitle: {
      "en-US": "What should you include?",
      "en-GB": "What should you include?",
      es: "¿Qué debería incluir?",
      fr: "Que faut-il inclure ?",
      de: "Was sollten Sie angeben?",
    },
    includeSubtitle: {
      "en-US": "A few details help us route your message quickly.",
      "en-GB": "A few details help us route your message quickly.",
      es: "Algunos detalles nos ayudan a dirigir su mensaje rápidamente.",
      fr: "Quelques détails nous aident à orienter votre message rapidement.",
      de: "Ein paar Details helfen uns, Ihre Nachricht schnell einzuordnen.",
    },
    hintTitle: {
      "en-US": "Prefer a quick start?",
      "en-GB": "Prefer a quick start?",
      es: "¿Prefiere empezar rápido?",
      fr: "Vous préférez aller vite ?",
      de: "Lieber direkt starten?",
    },
    hintBody: {
      "en-US":
        "For hiring requests, share your role requirements on For Companies. For candidates, browse Jobs.",
      "en-GB":
        "For hiring requests, share your role requirements on For Companies. For candidates, browse Jobs.",
      es: "Para solicitudes de contratación, comparta los requisitos del puesto en Para empresas. Para candidatos, consulte Empleos.",
      fr: "Pour une demande de recrutement, partagez vos besoins sur Pour les entreprises. Pour les candidats, consultez Offres.",
      de: "Für Hiring-Anfragen: teilen Sie Ihre Anforderungen unter Für Unternehmen. Für Kandidaten: sehen Sie sich Jobs an.",
    },
    formName: {
      "en-US": "Name",
      "en-GB": "Name",
      es: "Nombre",
      fr: "Nom",
      de: "Name",
    },
    formEmail: {
      "en-US": "Email",
      "en-GB": "Email",
      es: "Correo electrónico",
      fr: "E-mail",
      de: "E-Mail",
    },
    formTopic: {
      "en-US": "Topic",
      "en-GB": "Topic",
      es: "Tema",
      fr: "Sujet",
      de: "Thema",
    },
    formMessage: {
      "en-US": "Message",
      "en-GB": "Message",
      es: "Mensaje",
      fr: "Message",
      de: "Nachricht",
    },
    formSend: {
      "en-US": "Send message",
      "en-GB": "Send message",
      es: "Enviar mensaje",
      fr: "Envoyer le message",
      de: "Nachricht senden",
    },
    formPreview: {
      "en-US": "This form is currently in preview mode and doesn’t submit anywhere yet.",
      "en-GB": "This form is currently in preview mode and doesn’t submit anywhere yet.",
      es: "Este formulario está en modo de vista previa y todavía no envía a ningún lugar.",
      fr: "Ce formulaire est en mode aperçu et n’envoie rien pour le moment.",
      de: "Dieses Formular ist derzeit im Vorschaumodus und sendet noch nichts ab.",
    },
    metaTitle: {
      "en-US": "Contact",
      "en-GB": "Contact",
      es: "Contacto",
      fr: "Contact",
      de: "Kontakt",
    },
    metaDescription: {
      "en-US": "Contact NaviVision for hiring support, software partnerships, real estate, or investment inquiries.",
      "en-GB": "Contact NaviVision for hiring support, software partnerships, real estate, or investment enquiries.",
      es: "Contacte a NaviVision para apoyo de contratación, alianzas de software, bienes raíces o consultas de inversión.",
      fr: "Contactez NaviVision pour le recrutement, des partenariats logiciels, l’immobilier ou des questions d’investissement.",
      de: "Kontaktieren Sie NaviVision für Hiring-Support, Software-Partnerschaften, Immobilien oder Investment-Anfragen.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  talentHiring: {
    metaTitle: {
      "en-US": "Talent & Hiring",
      "en-GB": "Talent & Hiring",
      es: "Talento y contratación",
      fr: "Talent et recrutement",
      de: "Talent & Recruiting",
    },
    metaDescription: {
      "en-US":
        "NaviVision supports hiring for companies and helps talent find roles across our portfolio and partners.",
      "en-GB":
        "NaviVision supports hiring for companies and helps talent find roles across our portfolio and partners.",
      es: "NaviVision apoya la contratación para empresas y ayuda al talento a encontrar roles en nuestro portafolio y socios.",
      fr: "NaviVision accompagne le recrutement des entreprises et aide les talents à trouver des postes au sein de notre portefeuille et de nos partenaires.",
      de: "NaviVision unterstützt Unternehmen beim Hiring und hilft Talenten, passende Rollen im Portfolio und bei Partnern zu finden.",
    },
    kicker: {
      "en-US": "Talent & Hiring",
      "en-GB": "Talent & Hiring",
      es: "Talento y contratación",
      fr: "Talent et recrutement",
      de: "Talent & Recruiting",
    },
    title: {
      "en-US": "Hiring support for teams, and opportunities for talent.",
      "en-GB": "Hiring support for teams, and opportunities for talent.",
      es: "Apoyo de contratación para equipos y oportunidades para el talento.",
      fr: "Du recrutement pour les équipes et des opportunités pour les talents.",
      de: "Hiring-Support für Teams und Chancen für Talente.",
    },
    intro: {
      "en-US":
        "We run a high-signal process designed to move quickly without sacrificing quality. Whether you’re building a team or looking for your next role, we’ll meet you with clarity and follow-through.",
      "en-GB":
        "We run a high-signal process designed to move quickly without sacrificing quality. Whether you’re building a team or looking for your next role, we’ll meet you with clarity and follow-through.",
      es: "Operamos un proceso de alta señal pensado para avanzar rápido sin sacrificar calidad. Ya sea que esté formando un equipo o buscando su próximo rol, actuamos con claridad y seguimiento.",
      fr: "Nous proposons un processus à forte valeur de signal, conçu pour aller vite sans sacrifier la qualité. Que vous recrutiez ou cherchiez votre prochain poste, nous avançons avec clarté et suivi.",
      de: "Wir nutzen einen High-Signal-Prozess, der Geschwindigkeit ermöglicht, ohne Qualität zu opfern. Ob Teamaufbau oder nächste Rolle – wir arbeiten klar und verbindlich.",
    },
    ctaPrimary: {
      "en-US": "Talk to us",
      "en-GB": "Talk to us",
      es: "Hable con nosotros",
      fr: "Parlons-en",
      de: "Kontakt aufnehmen",
    },
    ctaSecondary: {
      "en-US": "View open roles",
      "en-GB": "View open roles",
      es: "Ver roles abiertos",
      fr: "Voir les postes ouverts",
      de: "Offene Rollen ansehen",
    },
    sectionTitle: {
      "en-US": "Built for speed and signal",
      "en-GB": "Built for speed and signal",
      es: "Diseñado para velocidad y señal",
      fr: "Conçu pour la vitesse et le signal",
      de: "Für Tempo und Signal gebaut",
    },
    sectionSubtitle: {
      "en-US": "Structured screening and a human candidate experience.",
      "en-GB": "Structured screening and a human candidate experience.",
      es: "Evaluación estructurada y una experiencia humana para candidatos.",
      fr: "Un screening structuré et une expérience candidat humaine.",
      de: "Strukturiertes Screening und eine menschliche Candidate Experience.",
    },
    pillar1Title: {
      "en-US": "Clear scorecards",
      "en-GB": "Clear scorecards",
      es: "Criterios claros",
      fr: "Scorecards claires",
      de: "Klare Scorecards",
    },
    pillar1Body: {
      "en-US": "We align on what “great” looks like and evaluate consistently.",
      "en-GB": "We align on what “great” looks like and evaluate consistently.",
      es: "Alineamos qué significa “excelente” y evaluamos de forma consistente.",
      fr: "Nous alignons la définition du “great” et évaluons de manière cohérente.",
      de: "Wir definieren gemeinsam, was “exzellent” bedeutet, und bewerten konsistent.",
    },
    pillar2Title: {
      "en-US": "Fast iteration",
      "en-GB": "Fast iteration",
      es: "Iteración rápida",
      fr: "Itération rapide",
      de: "Schnelle Iteration",
    },
    pillar2Body: {
      "en-US":
        "Weekly reporting, calibration, and message testing to improve response rates.",
      "en-GB":
        "Weekly reporting, calibration, and message testing to improve response rates.",
      es: "Reportes semanales, calibración y pruebas de mensajes para mejorar la tasa de respuesta.",
      fr: "Reporting hebdomadaire, calibrage et tests de messages pour améliorer les taux de réponse.",
      de: "Wöchentliche Reports, Kalibrierung und Messaging-Tests zur Steigerung der Response-Rate.",
    },
    pillar3Title: {
      "en-US": "Respect for time",
      "en-GB": "Respect for time",
      es: "Respeto por el tiempo",
      fr: "Respect du temps",
      de: "Respekt vor Zeit",
    },
    pillar3Body: {
      "en-US": "Fewer steps, better context, and timely communication.",
      "en-GB": "Fewer steps, better context, and timely communication.",
      es: "Menos pasos, mejor contexto y comunicación oportuna.",
      fr: "Moins d’étapes, plus de contexte et une communication réactive.",
      de: "Weniger Schritte, besserer Kontext und zeitnahe Kommunikation.",
    },
    exploreTitle: {
      "en-US": "Explore",
      "en-GB": "Explore",
      es: "Explorar",
      fr: "Découvrir",
      de: "Entdecken",
    },
    exploreSubtitle: {
      "en-US": "Choose your path.",
      "en-GB": "Choose your path.",
      es: "Elija su camino.",
      fr: "Choisissez votre voie.",
      de: "Wählen Sie Ihren Weg.",
    },
    cardCompaniesTitle: {
      "en-US": "For Companies",
      "en-GB": "For Companies",
      es: "Para empresas",
      fr: "Pour les entreprises",
      de: "Für Unternehmen",
    },
    cardCompaniesBody: {
      "en-US": "Role-based search, pipeline building, and hiring support.",
      "en-GB": "Role-based search, pipeline building, and hiring support.",
      es: "Búsqueda por rol, construcción de pipeline y apoyo de contratación.",
      fr: "Recherche par poste, construction de pipeline et accompagnement au recrutement.",
      de: "Rollenbasierte Suche, Pipeline-Aufbau und Hiring-Support.",
    },
    cardCompaniesLink: {
      "en-US": "Hiring support",
      "en-GB": "Hiring support",
      es: "Apoyo de contratación",
      fr: "Recrutement",
      de: "Hiring-Support",
    },
    cardTalentTitle: {
      "en-US": "For Talent",
      "en-GB": "For Talent",
      es: "Para talento",
      fr: "Pour les talents",
      de: "Für Talente",
    },
    cardTalentBody: {
      "en-US": "Browse roles and connect with teams we support.",
      "en-GB": "Browse roles and connect with teams we support.",
      es: "Explore roles y conéctese con equipos que apoyamos.",
      fr: "Découvrez des postes et connectez-vous aux équipes que nous accompagnons.",
      de: "Rollen ansehen und mit Teams in Kontakt treten, die wir unterstützen.",
    },
    cardTalentLink: {
      "en-US": "Candidate process",
      "en-GB": "Candidate process",
      es: "Proceso de candidatos",
      fr: "Process candidat",
      de: "Bewerbungsprozess",
    },
    cardJobsTitle: {
      "en-US": "Jobs",
      "en-GB": "Jobs",
      es: "Empleos",
      fr: "Offres",
      de: "Jobs",
    },
    cardJobsBody: {
      "en-US": "Open roles across our portfolio and partners.",
      "en-GB": "Open roles across our portfolio and partners.",
      es: "Roles abiertos en nuestro portafolio y socios.",
      fr: "Postes ouverts dans notre portefeuille et chez nos partenaires.",
      de: "Offene Rollen im Portfolio und bei Partnern.",
    },
    cardJobsLink: {
      "en-US": "View open roles",
      "en-GB": "View open roles",
      es: "Ver roles abiertos",
      fr: "Voir les postes",
      de: "Rollen ansehen",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  customSaas: {
    metaTitle: {
      "en-US": "Custom SaaS",
      "en-GB": "Custom SaaS",
      es: "SaaS a medida",
      fr: "SaaS sur mesure",
      de: "Individuelles SaaS",
    },
    metaDescription: {
      "en-US":
        "NaviVision builds and operates custom software and SaaS products with an operator’s focus on durability and outcomes.",
      "en-GB":
        "NaviVision builds and operates custom software and SaaS products with an operator’s focus on durability and outcomes.",
      es: "NaviVision construye y opera software a medida y productos SaaS con foco en durabilidad y resultados.",
      fr: "NaviVision conçoit et exploite des logiciels sur mesure et des produits SaaS, avec un focus sur la durabilité et les résultats.",
      de: "NaviVision entwickelt und betreibt individuelle Software und SaaS-Produkte – mit Fokus auf Langlebigkeit und Ergebnisse.",
    },
    kicker: {
      "en-US": "Custom SaaS",
      "en-GB": "Custom SaaS",
      es: "SaaS a medida",
      fr: "SaaS sur mesure",
      de: "Individuelles SaaS",
    },
    title: {
      "en-US": "Build software that compounds.",
      "en-GB": "Build software that compounds.",
      es: "Construya software que se acumula con el tiempo.",
      fr: "Construisez un logiciel qui crée de la valeur dans la durée.",
      de: "Bauen Sie Software, die langfristig wirkt.",
    },
    intro: {
      "en-US":
        "We design and build custom software, often as a path from internal tools to product. Our approach is pragmatic: ship quickly, measure impact, and invest in reliability.",
      "en-GB":
        "We design and build custom software, often as a path from internal tools to product. Our approach is pragmatic: ship quickly, measure impact, and invest in reliability.",
      es: "Diseñamos y construimos software a medida, a menudo como un camino desde herramientas internas hacia producto. Nuestro enfoque es pragmático: entregar rápido, medir impacto e invertir en confiabilidad.",
      fr: "Nous concevons et développons des logiciels sur mesure, souvent comme un chemin des outils internes vers le produit. Notre approche est pragmatique : livrer vite, mesurer l’impact et investir dans la fiabilité.",
      de: "Wir konzipieren und bauen individuelle Software – oft als Weg von internen Tools zum Produkt. Unser Ansatz ist pragmatisch: schnell liefern, Wirkung messen und in Zuverlässigkeit investieren.",
    },
    ctaPrimary: {
      "en-US": "Discuss a build",
      "en-GB": "Discuss a build",
      es: "Hablar de un proyecto",
      fr: "Discuter d’un projet",
      de: "Projekt besprechen",
    },
    ctaSecondary: {
      "en-US": "Software portfolio",
      "en-GB": "Software portfolio",
      es: "Portafolio de software",
      fr: "Portefeuille logiciel",
      de: "Software-Portfolio",
    },
    section1Title: {
      "en-US": "What we build",
      "en-GB": "What we build",
      es: "Qué construimos",
      fr: "Ce que nous construisons",
      de: "Was wir bauen",
    },
    section1Subtitle: {
      "en-US": "From internal tooling to customer-facing products.",
      "en-GB": "From internal tooling to customer-facing products.",
      es: "Desde herramientas internas hasta productos para clientes.",
      fr: "Des outils internes aux produits orientés clients.",
      de: "Von internen Tools bis zu kundenseitigen Produkten.",
    },
    card1Title: {
      "en-US": "Internal operating tools",
      "en-GB": "Internal operating tools",
      es: "Herramientas operativas internas",
      fr: "Outils opérationnels internes",
      de: "Interne Operating-Tools",
    },
    card1Body: {
      "en-US":
        "Dashboards, automations, and systems that remove manual work and improve visibility.",
      "en-GB":
        "Dashboards, automations, and systems that remove manual work and improve visibility.",
      es: "Paneles, automatizaciones y sistemas que eliminan trabajo manual y mejoran la visibilidad.",
      fr: "Tableaux de bord, automatisations et systèmes qui réduisent le manuel et améliorent la visibilité.",
      de: "Dashboards, Automatisierungen und Systeme, die manuelle Arbeit reduzieren und Transparenz schaffen.",
    },
    card2Title: {
      "en-US": "Customer portals",
      "en-GB": "Customer portals",
      es: "Portales para clientes",
      fr: "Portails clients",
      de: "Kundenportale",
    },
    card2Body: {
      "en-US": "Secure, modern experiences that make your service feel like product.",
      "en-GB": "Secure, modern experiences that make your service feel like product.",
      es: "Experiencias seguras y modernas que hacen que su servicio se sienta como producto.",
      fr: "Des expériences modernes et sécurisées qui transforment votre service en produit.",
      de: "Sichere, moderne Erlebnisse, die Ihren Service wie ein Produkt wirken lassen.",
    },
    card3Title: {
      "en-US": "SaaS products",
      "en-GB": "SaaS products",
      es: "Productos SaaS",
      fr: "Produits SaaS",
      de: "SaaS-Produkte",
    },
    card3Body: {
      "en-US":
        "Subscription software designed for retention, reliability, and measurable outcomes.",
      "en-GB":
        "Subscription software designed for retention, reliability, and measurable outcomes.",
      es: "Software por suscripción diseñado para retención, confiabilidad y resultados medibles.",
      fr: "Logiciels par abonnement conçus pour la rétention, la fiabilité et des résultats mesurables.",
      de: "Subscription-Software für Retention, Zuverlässigkeit und messbare Outcomes.",
    },
    section2Title: {
      "en-US": "How we engage",
      "en-GB": "How we engage",
      es: "Cómo trabajamos",
      fr: "Comment nous travaillons",
      de: "Wie wir zusammenarbeiten",
    },
    section2Subtitle: {
      "en-US": "A focused, operator-led process.",
      "en-GB": "A focused, operator-led process.",
      es: "Un proceso enfocado y liderado por operadores.",
      fr: "Un processus ciblé, mené par des opérateurs.",
      de: "Ein fokussierter, operator-geführter Prozess.",
    },
    step1Title: {
      "en-US": "Discovery sprint",
      "en-GB": "Discovery sprint",
      es: "Sprint de descubrimiento",
      fr: "Sprint de découverte",
      de: "Discovery-Sprint",
    },
    step1Body: {
      "en-US": "Align on users, workflows, constraints, and success metrics.",
      "en-GB": "Align on users, workflows, constraints, and success metrics.",
      es: "Alineamos usuarios, flujos de trabajo, restricciones y métricas de éxito.",
      fr: "Alignement sur les utilisateurs, les workflows, les contraintes et les métriques de succès.",
      de: "Alignment zu Nutzern, Workflows, Rahmenbedingungen und Erfolgsmetriken.",
    },
    step2Title: {
      "en-US": "Build + ship",
      "en-GB": "Build + ship",
      es: "Construir y entregar",
      fr: "Construire et livrer",
      de: "Bauen + liefern",
    },
    step2Body: {
      "en-US": "Deliver in small increments, validate quickly, and keep scope honest.",
      "en-GB": "Deliver in small increments, validate quickly, and keep scope honest.",
      es: "Entregamos en incrementos pequeños, validamos rápido y mantenemos el alcance realista.",
      fr: "Livrer par petits incréments, valider vite et garder un scope réaliste.",
      de: "In kleinen Inkrementen liefern, schnell validieren und Scope realistisch halten.",
    },
    step3Title: {
      "en-US": "Operate",
      "en-GB": "Operate",
      es: "Operar",
      fr: "Exploiter",
      de: "Betreiben",
    },
    step3Body: {
      "en-US":
        "Reliability, monitoring, security basics, and a plan to reduce support load.",
      "en-GB":
        "Reliability, monitoring, security basics, and a plan to reduce support load.",
      es: "Confiabilidad, monitoreo, bases de seguridad y un plan para reducir la carga de soporte.",
      fr: "Fiabilité, monitoring, fondamentaux de sécurité et plan pour réduire la charge support.",
      de: "Zuverlässigkeit, Monitoring, Security-Basics und ein Plan zur Reduktion der Supportlast.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  realEstate: {
    metaTitle: {
      "en-US": "Real Estate",
      "en-GB": "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      de: "Immobilien",
    },
    metaDescription: {
      "en-US":
        "NaviVision operates a long-term real estate portfolio with disciplined underwriting and operations.",
      "en-GB":
        "NaviVision operates a long-term real estate portfolio with disciplined underwriting and operations.",
      es: "NaviVision opera una cartera inmobiliaria a largo plazo con análisis y operación disciplinados.",
      fr: "NaviVision gère un portefeuille immobilier de long terme avec une discipline d’analyse et d’exploitation.",
      de: "NaviVision betreibt ein langfristiges Immobilienportfolio mit disziplinierter Analyse und Betrieb.",
    },
    kicker: {
      "en-US": "Real Estate",
      "en-GB": "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      de: "Immobilien",
    },
    title: {
      "en-US": "Long-term ownership, operated with care.",
      "en-GB": "Long-term ownership, operated with care.",
      es: "Propiedad a largo plazo, operada con cuidado.",
      fr: "Détention long terme, exploitée avec soin.",
      de: "Langfristiger Besitz, sorgfältig betrieben.",
    },
    intro: {
      "en-US":
        "We take an operator’s approach to real estate: conservative underwriting, proactive maintenance, and a commitment to the neighborhoods we’re part of.",
      "en-GB":
        "We take an operator’s approach to real estate: conservative underwriting, proactive maintenance, and a commitment to the neighbourhoods we’re part of.",
      es: "Adoptamos un enfoque operativo: análisis conservador, mantenimiento proactivo y compromiso con los vecindarios de los que formamos parte.",
      fr: "Nous adoptons une approche d’opérateur : analyse prudente, maintenance proactive et engagement envers les quartiers dont nous faisons partie.",
      de: "Wir verfolgen einen Operator-Ansatz: konservative Analyse, proaktive Instandhaltung und Verantwortung für die Standorte, in denen wir tätig sind.",
    },
    ctaPrimary: {
      "en-US": "Partnership inquiries",
      "en-GB": "Partnership enquiries",
      es: "Consultas de colaboración",
      fr: "Demandes de partenariat",
      de: "Kooperationsanfragen",
    },
    ctaSecondary: {
      "en-US": "Real estate portfolio",
      "en-GB": "Real estate portfolio",
      es: "Portafolio inmobiliario",
      fr: "Portefeuille immobilier",
      de: "Immobilienportfolio",
    },
    sectionTitle: {
      "en-US": "How we operate",
      "en-GB": "How we operate",
      es: "Cómo operamos",
      fr: "Comment nous opérons",
      de: "Wie wir betreiben",
    },
    sectionSubtitle: {
      "en-US": "Disciplined management that prioritizes durability.",
      "en-GB": "Disciplined management that prioritises durability.",
      es: "Gestión disciplinada que prioriza la durabilidad.",
      fr: "Une gestion disciplinée qui privilégie la durabilité.",
      de: "Disziplinierte Bewirtschaftung mit Fokus auf Langlebigkeit.",
    },
    card1Title: {
      "en-US": "Acquisition",
      "en-GB": "Acquisition",
      es: "Adquisición",
      fr: "Acquisition",
      de: "Akquisition",
    },
    card1Body: {
      "en-US": "Conservative assumptions and clear improvement plans when we buy.",
      "en-GB": "Conservative assumptions and clear improvement plans when we buy.",
      es: "Supuestos conservadores y planes de mejora claros al adquirir.",
      fr: "Hypothèses prudentes et plans d’amélioration clairs lors de l’acquisition.",
      de: "Konservative Annahmen und klare Verbesserungspläne beim Kauf.",
    },
    card2Title: {
      "en-US": "Operations",
      "en-GB": "Operations",
      es: "Operación",
      fr: "Exploitation",
      de: "Betrieb",
    },
    card2Body: {
      "en-US": "Reliable maintenance, responsive communication, and proactive risk management.",
      "en-GB": "Reliable maintenance, responsive communication, and proactive risk management.",
      es: "Mantenimiento confiable, comunicación ágil y gestión proactiva del riesgo.",
      fr: "Maintenance fiable, communication réactive et gestion proactive des risques.",
      de: "Zuverlässige Instandhaltung, schnelle Kommunikation und proaktives Risikomanagement.",
    },
    card3Title: {
      "en-US": "Reporting",
      "en-GB": "Reporting",
      es: "Reportes",
      fr: "Reporting",
      de: "Reporting",
    },
    card3Body: {
      "en-US": "Clear metrics and straightforward updates to support long-term decisions.",
      "en-GB": "Clear metrics and straightforward updates to support long-term decisions.",
      es: "Métricas claras y actualizaciones directas para apoyar decisiones de largo plazo.",
      fr: "Des métriques claires et des mises à jour simples pour soutenir les décisions long terme.",
      de: "Klare Kennzahlen und transparente Updates für langfristige Entscheidungen.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  investments: {
    metaTitle: {
      "en-US": "Investments",
      "en-GB": "Investments",
      es: "Inversiones",
      fr: "Investissements",
      de: "Investments",
    },
    metaDescription: {
      "en-US": "NaviVision invests selectively across startups and long-term operating assets.",
      "en-GB": "NaviVision invests selectively across startups and long-term operating assets.",
      es: "NaviVision invierte de forma selectiva en startups y activos operativos de largo plazo.",
      fr: "NaviVision investit de façon sélective dans des startups et des actifs opérés sur le long terme.",
      de: "NaviVision investiert selektiv in Start-ups und langfristige Operating Assets.",
    },
    kicker: {
      "en-US": "Investments",
      "en-GB": "Investments",
      es: "Inversiones",
      fr: "Investissements",
      de: "Investments",
    },
    title: {
      "en-US": "Targeted bets, backed by operators.",
      "en-GB": "Targeted bets, backed by operators.",
      es: "Apuestas selectivas, respaldadas por operadores.",
      fr: "Des paris ciblés, portés par des opérateurs.",
      de: "Gezielte Investments – von Operatoren begleitet.",
    },
    intro: {
      "en-US":
        "We invest with a long-term mindset and a preference for teams who ship. When it’s a fit, we contribute operational support, especially around product, hiring, and go-to-market clarity.",
      "en-GB":
        "We invest with a long-term mindset and a preference for teams who ship. When it’s a fit, we contribute operational support, especially around product, hiring, and go-to-market clarity.",
      es: "Invertimos con mentalidad de largo plazo y preferencia por equipos que ejecutan. Cuando hay encaje, aportamos apoyo operativo, especialmente en producto, contratación y claridad de go-to-market.",
      fr: "Nous investissons avec une vision long terme et une préférence pour les équipes qui livrent. Lorsque c’est pertinent, nous apportons un soutien opérationnel, notamment sur le produit, le recrutement et la clarté go-to-market.",
      de: "Wir investieren langfristig und bevorzugen Teams, die liefern. Wenn es passt, unterstützen wir operativ – insbesondere bei Produkt, Hiring und Go-to-Market-Klarheit.",
    },
    ctaPrimary: {
      "en-US": "Share your deck",
      "en-GB": "Share your deck",
      es: "Comparta su pitch deck",
      fr: "Partagez votre deck",
      de: "Pitch Deck senden",
    },
    ctaSecondary: {
      "en-US": "Investing approach",
      "en-GB": "Investing approach",
      es: "Enfoque de inversión",
      fr: "Approche d’investissement",
      de: "Investment-Ansatz",
    },
    sectionTitle: {
      "en-US": "What we look for",
      "en-GB": "What we look for",
      es: "Qué buscamos",
      fr: "Ce que nous recherchons",
      de: "Wonach wir suchen",
    },
    sectionSubtitle: {
      "en-US": "A simple filter: integrity, speed, and customer pull.",
      "en-GB": "A simple filter: integrity, speed, and customer pull.",
      es: "Un filtro simple: integridad, velocidad y tracción del cliente.",
      fr: "Un filtre simple : intégrité, vitesse et traction client.",
      de: "Ein einfacher Filter: Integrität, Tempo und Kundenzug.",
    },
    teamTitle: {
      "en-US": "Team",
      "en-GB": "Team",
      es: "Equipo",
      fr: "Équipe",
      de: "Team",
    },
    businessTitle: {
      "en-US": "Business",
      "en-GB": "Business",
      es: "Negocio",
      fr: "Entreprise",
      de: "Business",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  forCompanies: {
    metaTitle: {
      "en-US": "For Companies",
      "en-GB": "For Companies",
      es: "Para empresas",
      fr: "Pour les entreprises",
      de: "Für Unternehmen",
    },
    metaDescription: {
      "en-US":
        "Hire with confidence. NaviVision supports sourcing, screening, and hiring for teams that need execution-ready talent.",
      "en-GB":
        "Hire with confidence. NaviVision supports sourcing, screening, and hiring for teams that need execution-ready talent.",
      es: "Contrate con confianza. NaviVision apoya sourcing, evaluación y contratación para equipos que necesitan talento listo para ejecutar.",
      fr: "Recrutez en confiance. NaviVision accompagne le sourcing, le screening et le recrutement pour des équipes qui ont besoin de profils opérationnels.",
      de: "Stellen Sie mit Vertrauen ein. NaviVision unterstützt Sourcing, Screening und Hiring für Teams, die umsetzungsstarkes Talent brauchen.",
    },
    kicker: {
      "en-US": "For Companies",
      "en-GB": "For Companies",
      es: "Para empresas",
      fr: "Pour les entreprises",
      de: "Für Unternehmen",
    },
    title: {
      "en-US": "Hiring support that’s built for speed and signal.",
      "en-GB": "Hiring support that’s built for speed and signal.",
      es: "Apoyo de contratación diseñado para velocidad y señal.",
      fr: "Un recrutement conçu pour la vitesse et le signal.",
      de: "Hiring-Support, gebaut für Tempo und Signal.",
    },
    intro: {
      "en-US":
        "NaviVision helps organizations find and hire people who can execute. We focus on clarity, structured screening, and a high-touch process that respects both your time and the candidate experience.",
      "en-GB":
        "NaviVision helps organisations find and hire people who can execute. We focus on clarity, structured screening, and a high-touch process that respects both your time and the candidate experience.",
      es: "NaviVision ayuda a las organizaciones a encontrar y contratar personas que ejecutan. Nos enfocamos en claridad, evaluación estructurada y un proceso cercano que respeta su tiempo y la experiencia del candidato.",
      fr: "NaviVision aide les organisations à recruter des profils capables d’exécuter. Nous privilégions la clarté, un screening structuré et un processus attentionné qui respecte votre temps et l’expérience candidat.",
      de: "NaviVision hilft Organisationen, umsetzungsstarke Menschen zu finden und einzustellen. Wir setzen auf Klarheit, strukturiertes Screening und einen High-Touch-Prozess, der Zeit und Candidate Experience respektiert.",
    },
    ctaPrimary: {
      "en-US": "Request hiring support",
      "en-GB": "Request hiring support",
      es: "Solicitar apoyo de contratación",
      fr: "Demander un accompagnement",
      de: "Hiring-Support anfragen",
    },
    ctaSecondary: {
      "en-US": "Learn about our operators",
      "en-GB": "Learn about our operators",
      es: "Conozca a nuestros operadores",
      fr: "Découvrir nos opérateurs",
      de: "Über unsere Operatoren",
    },
    sectionTitle: {
      "en-US": "Engagement options",
      "en-GB": "Engagement options",
      es: "Opciones de colaboración",
      fr: "Modes d’intervention",
      de: "Zusammenarbeitsmodelle",
    },
    sectionSubtitle: {
      "en-US": "Flexible models: from urgent searches to ongoing pipelines.",
      "en-GB": "Flexible models: from urgent searches to ongoing pipelines.",
      es: "Modelos flexibles: desde búsquedas urgentes hasta pipelines continuos.",
      fr: "Des modèles flexibles : de la recherche urgente au pipeline continu.",
      de: "Flexible Modelle: von dringenden Suchen bis zu laufenden Pipelines.",
    },
    option1Title: {
      "en-US": "Role-based search",
      "en-GB": "Role-based search",
      es: "Búsqueda por rol",
      fr: "Recherche par poste",
      de: "Rollenbasierte Suche",
    },
    option1Body: {
      "en-US":
        "Targeted sourcing and screening for a specific role with clear scorecards and weekly updates.",
      "en-GB":
        "Targeted sourcing and screening for a specific role with clear scorecards and weekly updates.",
      es: "Sourcing y evaluación focalizados para un rol específico, con criterios claros y actualizaciones semanales.",
      fr: "Sourcing et screening ciblés pour un poste donné, avec scorecards claires et mises à jour hebdomadaires.",
      de: "Gezieltes Sourcing und Screening für eine konkrete Rolle – mit klaren Scorecards und wöchentlichen Updates.",
    },
    option2Title: {
      "en-US": "Pipeline build",
      "en-GB": "Pipeline build",
      es: "Construcción de pipeline",
      fr: "Construction de pipeline",
      de: "Pipeline-Aufbau",
    },
    option2Body: {
      "en-US":
        "Build a bench of pre-vetted candidates for recurring roles and forecasted hiring plans.",
      "en-GB":
        "Build a bench of pre-vetted candidates for recurring roles and forecasted hiring plans.",
      es: "Creamos una base de candidatos preevaluados para roles recurrentes y planes de contratación previstos.",
      fr: "Constituer un vivier de candidats préqualifiés pour des postes récurrents et des plans de recrutement.",
      de: "Aufbau eines Pools vorqualifizierter Kandidaten für wiederkehrende Rollen und geplante Einstellungsbedarfe.",
    },
    option3Title: {
      "en-US": "Team augmentation",
      "en-GB": "Team augmentation",
      es: "Refuerzo de equipo",
      fr: "Renfort d’équipe",
      de: "Team-Erweiterung",
    },
    option3Body: {
      "en-US":
        "Support short-term capacity needs with candidates who can start quickly and ramp fast.",
      "en-GB":
        "Support short-term capacity needs with candidates who can start quickly and ramp fast.",
      es: "Apoyamos necesidades de capacidad de corto plazo con candidatos que pueden comenzar y adaptarse rápido.",
      fr: "Répondre aux besoins de capacité court terme avec des profils disponibles et rapides à monter en puissance.",
      de: "Kurzfristige Kapazitätsbedarfe mit Kandidaten abdecken, die schnell starten und rasch produktiv werden.",
    },
    closingTitle: {
      "en-US": "Ready to hire?",
      "en-GB": "Ready to hire?",
      es: "¿Listo para contratar?",
      fr: "Prêt à recruter ?",
      de: "Bereit einzustellen?",
    },
    closingBody: {
      "en-US":
        "Tell us what you’re building, what “great” looks like for the role, and your timeline. We’ll respond with the next best step.",
      "en-GB":
        "Tell us what you’re building, what “great” looks like for the role, and your timeline. We’ll respond with the next best step.",
      es: "Cuéntenos qué está construyendo, qué significa “excelente” para el rol y su calendario. Le responderemos con el siguiente paso.",
      fr: "Dites-nous ce que vous construisez, ce que signifie “great” pour le poste et votre calendrier. Nous vous proposerons la meilleure prochaine étape.",
      de: "Sagen Sie uns, was Sie bauen, wie “exzellent” für die Rolle aussieht und Ihren Zeitplan. Wir melden uns mit dem nächsten sinnvollen Schritt.",
    },
    closingCtaPrimary: {
      "en-US": "Contact us",
      "en-GB": "Contact us",
      es: "Contáctenos",
      fr: "Contactez-nous",
      de: "Kontakt",
    },
    closingCtaSecondary: {
      "en-US": "View roles we’re hiring for",
      "en-GB": "View roles we’re hiring for",
      es: "Ver roles para los que estamos contratando",
      fr: "Voir les postes en cours",
      de: "Rollen ansehen, für die wir suchen",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  forTalent: {
    metaTitle: {
      "en-US": "For Talent",
      "en-GB": "For Talent",
      es: "Para talento",
      fr: "Pour les talents",
      de: "Für Talente",
    },
    metaDescription: {
      "en-US":
        "Find your next role. NaviVision connects talented people with teams building meaningful products and operations.",
      "en-GB":
        "Find your next role. NaviVision connects talented people with teams building meaningful products and operations.",
      es: "Encuentre su próximo rol. NaviVision conecta talento con equipos que construyen productos y operaciones significativas.",
      fr: "Trouvez votre prochain poste. NaviVision met en relation des talents avec des équipes qui construisent des produits et des opérations à impact.",
      de: "Finden Sie Ihre nächste Rolle. NaviVision verbindet Talente mit Teams, die sinnvolle Produkte und Prozesse aufbauen.",
    },
    kicker: {
      "en-US": "For Talent",
      "en-GB": "For Talent",
      es: "Para talento",
      fr: "Pour les talents",
      de: "Für Talente",
    },
    title: {
      "en-US": "Work that respects craft, clarity, and growth.",
      "en-GB": "Work that respects craft, clarity, and growth.",
      es: "Trabajo que respeta el oficio, la claridad y el crecimiento.",
      fr: "Un travail qui respecte le métier, la clarté et la progression.",
      de: "Arbeit, die Handwerk, Klarheit und Wachstum respektiert.",
    },
    intro: {
      "en-US":
        "We partner with teams that value strong communication and ownership. If you’re looking for your next opportunity, browse open roles or reach out to share what you’re looking for.",
      "en-GB":
        "We partner with teams that value strong communication and ownership. If you’re looking for your next opportunity, browse open roles or reach out to share what you’re looking for.",
      es: "Trabajamos con equipos que valoran la comunicación y la responsabilidad. Si busca su próxima oportunidad, revise roles abiertos o escríbanos para contar qué está buscando.",
      fr: "Nous travaillons avec des équipes qui valorisent la communication et l’ownership. Si vous cherchez votre prochaine opportunité, consultez les postes ouverts ou contactez-nous pour nous dire ce que vous recherchez.",
      de: "Wir arbeiten mit Teams, die starke Kommunikation und Ownership schätzen. Wenn Sie Ihre nächste Chance suchen, sehen Sie sich offene Rollen an oder melden Sie sich mit Ihren Zielen.",
    },
    ctaPrimary: {
      "en-US": "Browse open roles",
      "en-GB": "Browse open roles",
      es: "Ver roles abiertos",
      fr: "Voir les postes ouverts",
      de: "Offene Rollen ansehen",
    },
    ctaSecondary: {
      "en-US": "Introduce yourself",
      "en-GB": "Introduce yourself",
      es: "Presentarse",
      fr: "Se présenter",
      de: "Vorstellen",
    },
    sectionTitle: {
      "en-US": "How we work with candidates",
      "en-GB": "How we work with candidates",
      es: "Cómo trabajamos con candidatos",
      fr: "Notre processus candidat",
      de: "Wie wir mit Kandidaten arbeiten",
    },
    sectionSubtitle: {
      "en-US": "A straightforward process designed to minimize back-and-forth.",
      "en-GB": "A straightforward process designed to minimise back-and-forth.",
      es: "Un proceso directo diseñado para minimizar idas y vueltas.",
      fr: "Un processus simple, conçu pour limiter les allers-retours.",
      de: "Ein unkomplizierter Prozess, der Ping-Pong reduziert.",
    },
    card1Title: {
      "en-US": "Clarity up front",
      "en-GB": "Clarity up front",
      es: "Claridad desde el inicio",
      fr: "Clarté dès le départ",
      de: "Klarheit von Anfang an",
    },
    card1Body: {
      "en-US": "You’ll know the role expectations, compensation range, and interview steps early.",
      "en-GB": "You’ll know the role expectations, compensation range, and interview steps early.",
      es: "Conocerá pronto expectativas del rol, rango de compensación y etapas de entrevista.",
      fr: "Vous connaîtrez rapidement les attentes, la fourchette de rémunération et les étapes.",
      de: "Sie kennen früh Erwartungen, Gehaltsrahmen und Interview-Schritte.",
    },
    card2Title: {
      "en-US": "Signal over noise",
      "en-GB": "Signal over noise",
      es: "Señal sobre ruido",
      fr: "Le signal avant le bruit",
      de: "Signal statt Lärm",
    },
    card2Body: {
      "en-US":
        "Structured screening that focuses on real work, not trivia or endless rounds.",
      "en-GB":
        "Structured screening that focuses on real work, not trivia or endless rounds.",
      es: "Evaluación estructurada enfocada en trabajo real, no en trivia ni rondas interminables.",
      fr: "Un screening structuré centré sur le travail réel, pas sur la trivia ou des tours sans fin.",
      de: "Strukturiertes Screening mit Fokus auf echte Arbeit – nicht Trivia oder endlose Runden.",
    },
    card3Title: {
      "en-US": "Respectful follow-through",
      "en-GB": "Respectful follow-through",
      es: "Seguimiento respetuoso",
      fr: "Suivi respectueux",
      de: "Respektvolles Follow-up",
    },
    card3Body: {
      "en-US": "Timely feedback, clear next steps, and a process that treats your time as valuable.",
      "en-GB": "Timely feedback, clear next steps, and a process that treats your time as valuable.",
      es: "Feedback oportuno, próximos pasos claros y un proceso que valora su tiempo.",
      fr: "Un retour rapide, des prochaines étapes claires et un processus qui respecte votre temps.",
      de: "Zeitnahes Feedback, klare nächste Schritte und ein Prozess, der Ihre Zeit respektiert.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  jobs: {
    metaTitle: {
      "en-US": "Jobs",
      "en-GB": "Jobs",
      es: "Empleos",
      fr: "Offres",
      de: "Jobs",
    },
    metaDescription: {
      "en-US": "Browse open roles across NaviVision’s portfolio and hiring partners.",
      "en-GB": "Browse open roles across NaviVision’s portfolio and hiring partners.",
      es: "Explore roles abiertos en el portafolio de NaviVision y socios de contratación.",
      fr: "Consultez les postes ouverts au sein du portefeuille de NaviVision et de nos partenaires.",
      de: "Sehen Sie offene Rollen im NaviVision-Portfolio und bei Hiring-Partnern.",
    },
    kicker: {
      "en-US": "Jobs",
      "en-GB": "Jobs",
      es: "Empleos",
      fr: "Offres",
      de: "Jobs",
    },
    title: {
      "en-US": "Open roles across our portfolio.",
      "en-GB": "Open roles across our portfolio.",
      es: "Roles abiertos en nuestro portafolio.",
      fr: "Postes ouverts dans notre portefeuille.",
      de: "Offene Rollen in unserem Portfolio.",
    },
    intro: {
      "en-US":
        "This page is a lightweight starting point. If you don’t see a perfect match, reach out. Strong candidates are often considered for upcoming roles.",
      "en-GB":
        "This page is a lightweight starting point. If you don’t see a perfect match, reach out. Strong candidates are often considered for upcoming roles.",
      es: "Esta página es un punto de partida. Si no ve un encaje perfecto, escríbanos. A menudo consideramos buenos perfiles para roles próximos.",
      fr: "Cette page est un point de départ. Si vous ne voyez pas un match parfait, contactez-nous. Les bons profils sont souvent considérés pour des postes à venir.",
      de: "Diese Seite ist ein Einstieg. Wenn keine Rolle perfekt passt, melden Sie sich. Starke Kandidaten berücksichtigen wir häufig auch für kommende Rollen.",
    },
    ctaPrimary: {
      "en-US": "Submit interest",
      "en-GB": "Submit interest",
      es: "Enviar interés",
      fr: "Manifester votre intérêt",
      de: "Interesse bekunden",
    },
    ctaSecondary: {
      "en-US": "Candidate process",
      "en-GB": "Candidate process",
      es: "Proceso de candidatos",
      fr: "Process candidat",
      de: "Bewerbungsprozess",
    },
    sectionTitle: {
      "en-US": "Current openings",
      "en-GB": "Current openings",
      es: "Vacantes actuales",
      fr: "Postes ouverts",
      de: "Aktuelle Stellen",
    },
    sectionSubtitle: {
      "en-US": "Example roles to illustrate the kinds of teams we support.",
      "en-GB": "Example roles to illustrate the kinds of teams we support.",
      es: "Roles de ejemplo para ilustrar los equipos que apoyamos.",
      fr: "Exemples de postes pour illustrer les équipes que nous accompagnons.",
      de: "Beispielrollen, die zeigen, welche Teams wir unterstützen.",
    },
    applyLink: {
      "en-US": "Apply / inquire",
      "en-GB": "Apply / enquire",
      es: "Postular / consultar",
      fr: "Candidater / demander",
      de: "Bewerben / anfragen",
    },
    hiringHelpLink: {
      "en-US": "Hiring help",
      "en-GB": "Hiring help",
      es: "Ayuda de contratación",
      fr: "Aide au recrutement",
      de: "Hiring-Hilfe",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  portfolio: {
    metaTitle: {
      "en-US": "Portfolio",
      "en-GB": "Portfolio",
      es: "Portafolio",
      fr: "Portefeuille",
      de: "Portfolio",
    },
    metaDescription: {
      "en-US":
        "An overview of NaviVision’s operating focus across software, real estate, and investments.",
      "en-GB":
        "An overview of NaviVision’s operating focus across software, real estate, and investments.",
      es: "Una visión general del enfoque operativo de NaviVision en software, bienes raíces e inversiones.",
      fr: "Aperçu de l’approche opérationnelle de NaviVision autour des logiciels, de l’immobilier et des investissements.",
      de: "Ein Überblick über NaviVisions operativen Fokus auf Software, Immobilien und Investments.",
    },
    kicker: {
      "en-US": "Portfolio",
      "en-GB": "Portfolio",
      es: "Portafolio",
      fr: "Portefeuille",
      de: "Portfolio",
    },
    title: {
      "en-US": "Businesses we build, operate, and support.",
      "en-GB": "Businesses we build, operate, and support.",
      es: "Negocios que construimos, operamos y apoyamos.",
      fr: "Des entreprises que nous construisons, exploitons et accompagnons.",
      de: "Unternehmen, die wir aufbauen, betreiben und unterstützen.",
    },
    intro: {
      "en-US":
        "NaviVision has expansive ownership across a range of companies. We also operate a real estate portfolio and invest in early-stage startups.",
      "en-GB":
        "NaviVision has expansive ownership across a range of companies. We also operate a real estate portfolio and invest in early-stage startups.",
      es: "NaviVision tiene participaciones en una variedad de compañías. También operamos una cartera inmobiliaria e invertimos en startups en etapa temprana.",
      fr: "NaviVision détient des participations dans plusieurs entreprises. Nous gérons également un portefeuille immobilier et investissons dans des startups early stage.",
      de: "NaviVision hält Beteiligungen an verschiedenen Unternehmen. Wir betreiben außerdem ein Immobilienportfolio und investieren in Early-Stage-Start-ups.",
    },
    ctaPrimary: {
      "en-US": "Partnership inquiries",
      "en-GB": "Partnership enquiries",
      es: "Consultas de colaboración",
      fr: "Demandes de partenariat",
      de: "Kooperationsanfragen",
    },
    ctaSecondary: {
      "en-US": "About NaviVision",
      "en-GB": "About NaviVision",
      es: "Acerca de NaviVision",
      fr: "À propos de NaviVision",
      de: "Über NaviVision",
    },
    softwareTitle: {
      "en-US": "Software & SaaS",
      "en-GB": "Software & SaaS",
      es: "Software y SaaS",
      fr: "Logiciels et SaaS",
      de: "Software & SaaS",
    },
    softwareSubtitle: {
      "en-US": "Products that solve real operational problems.",
      "en-GB": "Products that solve real operational problems.",
      es: "Productos que resuelven problemas operativos reales.",
      fr: "Des produits qui résolvent de vrais problèmes opérationnels.",
      de: "Produkte, die echte operative Probleme lösen.",
    },
    softwareCard1Title: {
      "en-US": "Operating systems",
      "en-GB": "Operating systems",
      es: "Sistemas operativos",
      fr: "Systèmes d’exploitation",
      de: "Operating Systems",
    },
    softwareCard1Body: {
      "en-US":
        "Internal and customer-facing software designed to automate workflow and improve visibility.",
      "en-GB":
        "Internal and customer-facing software designed to automate workflow and improve visibility.",
      es: "Software interno y para clientes diseñado para automatizar flujos de trabajo y mejorar la visibilidad.",
      fr: "Logiciels internes et orientés clients conçus pour automatiser les workflows et améliorer la visibilité.",
      de: "Interne und kundenseitige Software zur Automatisierung von Workflows und für mehr Transparenz.",
    },
    softwareCard2Title: {
      "en-US": "SaaS products",
      "en-GB": "SaaS products",
      es: "Productos SaaS",
      fr: "Produits SaaS",
      de: "SaaS-Produkte",
    },
    softwareCard2Body: {
      "en-US":
        "Subscription businesses with a focus on retention, reliability, and measurable outcomes.",
      "en-GB":
        "Subscription businesses with a focus on retention, reliability, and measurable outcomes.",
      es: "Negocios por suscripción con foco en retención, confiabilidad y resultados medibles.",
      fr: "Des activités par abonnement axées sur la rétention, la fiabilité et des résultats mesurables.",
      de: "Subscription-Geschäftsmodelle mit Fokus auf Retention, Zuverlässigkeit und messbare Outcomes.",
    },
    softwareCard3Title: {
      "en-US": "Services-to-software",
      "en-GB": "Services-to-software",
      es: "De servicios a software",
      fr: "Du service au logiciel",
      de: "Service-to-Software",
    },
    softwareCard3Body: {
      "en-US":
        "We turn repeatable service playbooks into software products when the economics and user demand align.",
      "en-GB":
        "We turn repeatable service playbooks into software products when the economics and user demand align.",
      es: "Convertimos playbooks de servicios repetibles en productos de software cuando la economía y la demanda se alinean.",
      fr: "Nous transformons des playbooks de services reproductibles en produits logiciels lorsque l’économie et la demande s’alignent.",
      de: "Wir verwandeln wiederholbare Service-Playbooks in Softwareprodukte, wenn Wirtschaftlichkeit und Nachfrage passen.",
    },
    realEstateTitle: {
      "en-US": "Real Estate",
      "en-GB": "Real Estate",
      es: "Bienes raíces",
      fr: "Immobilier",
      de: "Immobilien",
    },
    realEstateSubtitle: {
      "en-US": "Long-term ownership with an operator’s discipline.",
      "en-GB": "Long-term ownership with an operator’s discipline.",
      es: "Propiedad a largo plazo con disciplina operativa.",
      fr: "Détention long terme avec une discipline d’opérateur.",
      de: "Langfristiger Besitz mit operativer Disziplin.",
    },
    reCard1Title: {
      "en-US": "Acquisition",
      "en-GB": "Acquisition",
      es: "Adquisición",
      fr: "Acquisition",
      de: "Akquisition",
    },
    reCard1Body: {
      "en-US":
        "Conservative underwriting with a preference for stable demand drivers and clear path-to-improvement.",
      "en-GB":
        "Conservative underwriting with a preference for stable demand drivers and clear path-to-improvement.",
      es: "Análisis conservador, preferencia por demanda estable y un camino claro de mejora.",
      fr: "Analyse prudente, préférence pour des moteurs de demande stables et une voie claire d’amélioration.",
      de: "Konservative Analyse, bevorzugt stabile Nachfragetreiber und klare Verbesserungshebel.",
    },
    reCard2Title: {
      "en-US": "Operations",
      "en-GB": "Operations",
      es: "Operación",
      fr: "Exploitation",
      de: "Betrieb",
    },
    reCard2Body: {
      "en-US":
        "Reliable maintenance, responsive communication, and a proactive approach to preserving value.",
      "en-GB":
        "Reliable maintenance, responsive communication, and a proactive approach to preserving value.",
      es: "Mantenimiento confiable, comunicación ágil y enfoque proactivo para preservar valor.",
      fr: "Maintenance fiable, communication réactive et approche proactive pour préserver la valeur.",
      de: "Zuverlässige Instandhaltung, schnelle Kommunikation und proaktives Werterhaltungsmanagement.",
    },
    reCard3Title: {
      "en-US": "Portfolio management",
      "en-GB": "Portfolio management",
      es: "Gestión de portafolio",
      fr: "Gestion du portefeuille",
      de: "Portfoliomanagement",
    },
    reCard3Body: {
      "en-US": "A long-term mindset paired with clear reporting and risk controls.",
      "en-GB": "A long-term mindset paired with clear reporting and risk controls.",
      es: "Mentalidad de largo plazo con reportes claros y controles de riesgo.",
      fr: "Une vision long terme avec un reporting clair et des contrôles de risque.",
      de: "Langfristige Perspektive kombiniert mit klarem Reporting und Risikokontrollen.",
    },
    investingTitle: {
      "en-US": "Startup Investing",
      "en-GB": "Startup investing",
      es: "Inversión en startups",
      fr: "Investissement startups",
      de: "Startup-Investing",
    },
    investingSubtitle: {
      "en-US": "We invest selectively and support founders who ship.",
      "en-GB": "We invest selectively and support founders who ship.",
      es: "Invertimos de forma selectiva y apoyamos a fundadores que ejecutan.",
      fr: "Nous investissons de façon sélective et soutenons des fondateurs qui livrent.",
      de: "Wir investieren selektiv und unterstützen Gründer, die liefern.",
    },
    lookForTitle: {
      "en-US": "What we look for",
      "en-GB": "What we look for",
      es: "Qué buscamos",
      fr: "Ce que nous recherchons",
      de: "Wonach wir suchen",
    },
    helpTitle: {
      "en-US": "How we help",
      "en-GB": "How we help",
      es: "Cómo ayudamos",
      fr: "Comment nous aidons",
      de: "Wie wir helfen",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  privacy: {
    metaTitle: {
      "en-US": "Privacy",
      "en-GB": "Privacy",
      es: "Privacidad",
      fr: "Confidentialité",
      de: "Datenschutz",
    },
    metaDescription: {
      "en-US": "Privacy policy for NaviVision.",
      "en-GB": "Privacy policy for NaviVision.",
      es: "Política de privacidad de NaviVision.",
      fr: "Politique de confidentialité de NaviVision.",
      de: "Datenschutzerklärung von NaviVision.",
    },
    kicker: {
      "en-US": "Privacy",
      "en-GB": "Privacy",
      es: "Privacidad",
      fr: "Confidentialité",
      de: "Datenschutz",
    },
    title: {
      "en-US": "Privacy Policy",
      "en-GB": "Privacy Policy",
      es: "Política de privacidad",
      fr: "Politique de confidentialité",
      de: "Datenschutzerklärung",
    },
    intro: {
      "en-US":
        "This site is a marketing experience for NaviVision. We keep data collection minimal and use it to operate and improve the site.",
      "en-GB":
        "This site is a marketing experience for NaviVision. We keep data collection minimal and use it to operate and improve the site.",
      es: "Este sitio es una experiencia de marketing de NaviVision. Mantenemos la recopilación de datos al mínimo y la usamos para operar y mejorar el sitio.",
      fr: "Ce site est une expérience marketing de NaviVision. Nous limitons la collecte de données au strict minimum et l’utilisons pour exploiter et améliorer le site.",
      de: "Diese Website ist eine Marketingpräsenz von NaviVision. Wir erheben so wenige Daten wie möglich und nutzen sie, um die Website zu betreiben und zu verbessern.",
    },
    section1Title: {
      "en-US": "Information we collect",
      "en-GB": "Information we collect",
      es: "Información que recopilamos",
      fr: "Informations que nous collectons",
      de: "Welche Daten wir erfassen",
    },
    section2Title: {
      "en-US": "How we use information",
      "en-GB": "How we use information",
      es: "Cómo usamos la información",
      fr: "Comment nous utilisons ces informations",
      de: "Wie wir Daten verwenden",
    },
    section3Title: {
      "en-US": "Contact",
      "en-GB": "Contact",
      es: "Contacto",
      fr: "Contact",
      de: "Kontakt",
    },
    li1: {
      "en-US": "Information you provide via contact forms (if enabled).",
      "en-GB": "Information you provide via contact forms (if enabled).",
      es: "Información que usted proporciona mediante formularios de contacto (si están habilitados).",
      fr: "Les informations que vous fournissez via les formulaires de contact (si activés).",
      de: "Informationen, die Sie über Kontaktformulare bereitstellen (falls aktiviert).",
    },
    li2: {
      "en-US": "Basic, aggregated usage metrics (if analytics are enabled).",
      "en-GB": "Basic, aggregated usage metrics (if analytics are enabled).",
      es: "Métricas básicas y agregadas de uso (si el análisis está habilitado).",
      fr: "Des métriques d’usage basiques et agrégées (si l’analytics est activé).",
      de: "Grundlegende, aggregierte Nutzungsmetriken (falls Analytics aktiviert sind).",
    },
    li3: {
      "en-US": "To respond to requests and inquiries.",
      "en-GB": "To respond to requests and inquiries.",
      es: "Para responder a solicitudes y consultas.",
      fr: "Pour répondre aux demandes et sollicitations.",
      de: "Zur Beantwortung von Anfragen.",
    },
    li4: {
      "en-US": "To operate, secure, and improve our services.",
      "en-GB": "To operate, secure, and improve our services.",
      es: "Para operar, proteger y mejorar nuestros servicios.",
      fr: "Pour exploiter, sécuriser et améliorer nos services.",
      de: "Zum Betrieb, zur Absicherung und zur Verbesserung unserer Services.",
    },
    contactBody: {
      "en-US": "Questions about this policy can be sent through the contact page.",
      "en-GB": "Questions about this policy can be sent through the contact page.",
      es: "Las preguntas sobre esta política pueden enviarse a través de la página de contacto.",
      fr: "Les questions concernant cette politique peuvent être envoyées via la page de contact.",
      de: "Fragen zu dieser Richtlinie können über die Kontaktseite gestellt werden.",
    },
    disclaimer: {
      "en-US": "This policy is a starting template and should be reviewed by counsel before production use.",
      "en-GB": "This policy is a starting template and should be reviewed by counsel before production use.",
      es: "Esta política es una plantilla inicial y debe ser revisada por asesoría legal antes de usarla en producción.",
      fr: "Cette politique est un modèle de départ et doit être revue par un conseil juridique avant utilisation en production.",
      de: "Diese Richtlinie ist eine Vorlage und sollte vor dem Produktiveinsatz rechtlich geprüft werden.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  terms: {
    metaTitle: {
      "en-US": "Terms",
      "en-GB": "Terms",
      es: "Términos",
      fr: "Conditions",
      de: "AGB",
    },
    metaDescription: {
      "en-US": "Terms of service for NaviVision.",
      "en-GB": "Terms of service for NaviVision.",
      es: "Términos de servicio de NaviVision.",
      fr: "Conditions d’utilisation de NaviVision.",
      de: "Nutzungsbedingungen von NaviVision.",
    },
    kicker: {
      "en-US": "Terms",
      "en-GB": "Terms",
      es: "Términos",
      fr: "Conditions",
      de: "AGB",
    },
    title: {
      "en-US": "Terms of Service",
      "en-GB": "Terms of Service",
      es: "Términos de servicio",
      fr: "Conditions d’utilisation",
      de: "Nutzungsbedingungen",
    },
    intro: {
      "en-US":
        "These terms are a simple placeholder for a marketing site. Update them to reflect your actual services, policies, and legal requirements.",
      "en-GB":
        "These terms are a simple placeholder for a marketing site. Update them to reflect your actual services, policies, and legal requirements.",
      es: "Estos términos son un texto de ejemplo para un sitio de marketing. Actualícelos para reflejar sus servicios, políticas y requisitos legales reales.",
      fr: "Ces conditions sont un exemple pour un site marketing. Mettez-les à jour pour refléter vos services, politiques et obligations légales réels.",
      de: "Diese Bedingungen sind ein Platzhalter für eine Marketing-Website. Bitte an Ihre tatsächlichen Services, Richtlinien und rechtlichen Anforderungen anpassen.",
    },
    section1Title: {
      "en-US": "Use of site",
      "en-GB": "Use of site",
      es: "Uso del sitio",
      fr: "Utilisation du site",
      de: "Nutzung der Website",
    },
    section1Body: {
      "en-US":
        "You may use this site for informational purposes. Do not misuse the site or attempt to disrupt its operation.",
      "en-GB":
        "You may use this site for informational purposes. Do not misuse the site or attempt to disrupt its operation.",
      es: "Puede usar este sitio con fines informativos. No haga un uso indebido ni intente interrumpir su funcionamiento.",
      fr: "Vous pouvez utiliser ce site à des fins d’information. Ne l’utilisez pas de manière abusive et ne tentez pas d’en perturber le fonctionnement.",
      de: "Sie dürfen diese Website zu Informationszwecken nutzen. Bitte missbrauchen Sie die Website nicht und versuchen Sie nicht, den Betrieb zu stören.",
    },
    section2Title: {
      "en-US": "No warranty",
      "en-GB": "No warranty",
      es: "Sin garantía",
      fr: "Aucune garantie",
      de: "Keine Gewährleistung",
    },
    section2Body: {
      "en-US": "The site is provided “as is” without warranties of any kind.",
      "en-GB": "The site is provided “as is” without warranties of any kind.",
      es: "El sitio se proporciona “tal cual”, sin garantías de ningún tipo.",
      fr: "Le site est fourni « en l’état » sans garantie d’aucune sorte.",
      de: "Die Website wird „wie besehen“ ohne jegliche Gewährleistung bereitgestellt.",
    },
    section3Title: {
      "en-US": "Contact",
      "en-GB": "Contact",
      es: "Contacto",
      fr: "Contact",
      de: "Kontakt",
    },
    section3Body: {
      "en-US": "For questions, use the contact page.",
      "en-GB": "For questions, use the contact page.",
      es: "Para preguntas, use la página de contacto.",
      fr: "Pour toute question, utilisez la page de contact.",
      de: "Bei Fragen nutzen Sie bitte die Kontaktseite.",
    },
  } satisfies Record<string, CopyByLocale<string>>,

  notFound: {
    title: {
      "en-US": "Page not found",
      "en-GB": "Page not found",
      es: "Página no encontrada",
      fr: "Page introuvable",
      de: "Seite nicht gefunden",
    },
    body: {
      "en-US": "The page you’re looking for doesn’t exist or has moved.",
      "en-GB": "The page you’re looking for doesn’t exist or has moved.",
      es: "La página que busca no existe o se ha movido.",
      fr: "La page que vous cherchez n’existe pas ou a été déplacée.",
      de: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
    },
    ctaHome: {
      "en-US": "Back home",
      "en-GB": "Back home",
      es: "Volver al inicio",
      fr: "Retour à l’accueil",
      de: "Zur Startseite",
    },
    ctaContact: {
      "en-US": "Contact",
      "en-GB": "Contact",
      es: "Contacto",
      fr: "Contact",
      de: "Kontakt",
    },
  } satisfies Record<string, CopyByLocale<string>>,
} as const;

export function c<T extends Record<Locale, string>>(value: T, locale: Locale): string {
  return value[locale] ?? value["en-US"];
}
